### PR TITLE
Retain genre selection on reopenning checkout modal

### LINKED ISSUE #132: Genres are forgotten if modal is closed
Steps to reproduce:

1. Select some genres in the modal
2. Close the modal with the 'X' button
3. Click Continue to reopen the modal
4. The genres are no longer selected, but the bottom Subscribe button still shows the total price.

### PR DESCRIPTION
**Pull request by irshadjsr21**
Fixes #132

### CODE REVIEW

**Comment by hmajid2301** [comment]
Since this is being merged into the billsyby branch and not master. I'm ok with the CI failing. But it looks like the the CI workflow is out of date. So on the billsyby branch you will have to pull in the latest changes.

**Comment by irshadjsr21** [comment]
> Why is there a `package-lock.json` file now ? Have we swapped to using `npm` ?

I use `npm` personally. Do you want me to remove `package-lock.json`?

**Comment by hmajid2301** [comment]
I'm happy to use either yarn or npm. I believe yarn is currently being used. Want to open it as a poll on Slack ? Just need to make sure we're consistent from now on.

**Comment by irshadjsr21** [comment]
It's stick with what's already there in the current setup.

**Comment by irshadjsr21** [comment]
@hmajid2301 Please merge it if you feel everything is fine.

**Pull request merged**
