### PR TITLE
feat: Separate pages for charity modals

### PR DESCRIPTION
**Pull request by gigarthan**

### CODE REVIEW

**Comment by kelvinlockwood** [comment]
This PR adds "instagram style modals" much the same as described here... https://youtu.be/EyjuRCxpf6Y

It means each charity can have its own dedicated url, for example: https://deploy-preview-167--quizzical-minsky-8b8868.netlify.app/tenovus-cancer-care#cheshire

**Comment by hmajid2301** [comment]
@gigarthan  It looks good have you tested this on Firefox ? I see the following https://youtu.be/9TXn-0quo8A

**Review by hmajid2301 — COMMENTED** [review]
Why did you delete the .github folder ?

**Comment by gigarthan** [comment]
> @gigarthan It looks good have you tested this on Firefox ? I see the following https://youtu.be/9TXn-0quo8A

No, it was mainly tested on chrome & chromium based browsers

**Comment by gigarthan** [comment]
> Why did you delete the .github folder ?

it must have been deleted or missed while I was cloning the repo.

**Comment by hmajid2301** [comment]
> > Why did you delete the .github folder ?
> 
> it must have been deleted or missed while I was cloning the repo.

Please add it back in

**Pull request merged**
