### PR TITLE
Added billsby self service

### LINKED ISSUE #143: Enable Billsby's self-service
We did have a Log in button alongside the Share button but it is currently hidden.

That button will allow the user to access Billsby's self-service portal to manage their subscription so it needs to be in place when we can go live. The self-service portal gives the customer the chance to change their payment or order details.

The embed code is explained here > https://support.billsby.com/docs/change-plan

We can also add a 'Manage subscription' link in the footer.

### PR DESCRIPTION
**Pull request by irshadjsr21**
Fixes #143

Added billsby self-service in the footer.

Adding a button beside the current share button doesn't look right. It's taking too much space in the floating area (especially in the mobile view). Maybe we need to readjust the share button or find another place for the `Manage your subscription` button.

### CODE REVIEW

**Comment by hmajid2301** [comment]
is this ready to merge ?

**Comment by kelvinlockwood** [comment]
@irshadjsr21 only the share button should float, the Log in button scrolls away.

I was imagining 'Manage your subscription' to be another link in the footer, rather than a button, but happy to review other ideas you have for it. Simple will suffice for now.

**Comment by kelvinlockwood** [comment]
@irshadjsr21 it will probably look better if we remove the drop shadow / shaded border area...

Screen Shot 2020-06-03 at 23 36 07

**Comment by irshadjsr21** [comment]
@kelvinlockwood From the issue description what I got was we need the self service in the footer and beside the share button.

The footer link is added. But I'm not able to adjust the button on the header. Maybe if you provide an image of what it should look like then I can implement it.

Also I didn't find any commented out code for the login button that you where referring to.

**Comment by kelvinlockwood** [comment]
@irshadjsr21 I would apply the same basic style as the Share button but with the addition of a hover effect... hover could invert the buttons colours (the button becomes the text colour and the text becomes white) OR display an outline around the button...

Needs to be in sentence case... Log in

**Comment by irshadjsr21** [comment]
@kelvinlockwood I get the style of the button. I'm having a problem with the button's position.

**Comment by irshadjsr21** [comment]
@engjellselaci Can you try to fit the `Log in` button on the header?

**Pull request merged**
